/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Pretendard', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'system-ui', 'Roboto', 'Helvetica Neue', 'Segoe UI', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Malgun Gothic', 'sans-serif'],
      },
      borderRadius: {
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      fontSize: {
        'h1-mobile': '2rem',
        'h1-tablet': '2.5rem',
        'h1': '3rem',
        'h2-mobile': '1.75rem',
        'h2-tablet': '2rem',
        'h2': '2.25rem',
        'h3-mobile': '1.375rem',
        'h3-tablet': '1.5rem',
        'h3': '1.75rem',
        'h4-mobile': '1.125rem',
        'h4-tablet': '1.25rem',
        'h4': '1.375rem',
        'h5-mobile': '1rem',
        'h5-tablet': '1.063rem',
        'h5': '1.125rem',
        'h6': '1rem',
        'body-lg': '1.125rem',
        'body-base': '1rem',
        'body-sm': '0.875rem',
        'caption': '0.75rem',
        'fine-print': '0.6875rem'
      },
      lineHeight: {
        'tighter': '1.1',
        'tight': '1.2',
        'snug': '1.3',
        'normal': '1.4',
        'relaxed': '1.6',
      },
      letterSpacing: {
        'tight-title': '-0.02em',
        'normal': '0em',
        'wide-caption': '0.01em',
      },
      colors: {
        'apx-growth-green': '#4AA966',
        'apx-deep-growth': '#2D5A3D',
        'apx-primary-yellow': '#FEFBEB',
        'apx-foundation-beige': '#F9F5EB',
        'strategy-blue': '#2B4A73',
        'talent-orange': '#D67E3B',
        'process-gray': '#5A6C7D',
        'leadership-navy': '#2B4A73',
        'operation-gray': '#5A6C7D',
        'culture-coral': '#E07A5F',
        'performance-green': '#4AA966',
        'analytics-teal': '#4A9B8E',
        'diagnosis-blue': '#4A7C89',
        'design-purple': '#8B5A9F',
        'execution-red': '#C85C5C',
        'text-primary': '#111827',
        'text-secondary': '#4B5563',
        'text-tertiary': '#9CA3AF',
        'bg-primary': '#FFFFFF',
        'bg-secondary': '#F9FAFB',
        'bg-dark': '#111827',
        'success': '#4AA966',
        'warning': '#D69E2E',
        'error': '#E53E3E',
        'info': '#3182CE',
        'border-light': '#E5E7EB',
      }
    }
  },
  plugins: [],
}